package com.supplychain.domain.merkle;

import com.supplychain.crypto.HashFunction;
import com.supplychain.crypto.Sha256Hasher;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Domain Layer — Merkle Tree
 * ===========================
 *
 * A binary hash tree enabling O(log n) verification that a piece of data
 * belongs to a committed set:
 *
 * - LEAVES:        individual transaction hashes
 * - INTERNAL NODES: hash of the concatenated child hashes
 * - ROOT:          a single hash summarizing the entire set
 *
 * COMPLEXITY:
 * - Building the tree:            O(n) time, O(n) space
 * - Generating a proof:           O(log n) time
 * - Verifying a proof:            O(log n) time
 *
 * This is what lets a lightweight consumer verify a product's
 * authenticity without downloading the full transaction history.
 */
public class MerkleTree {

    private final HashFunction hasher;
    private final List<String> leaves;
    private MerkleNode root;

    /**
     * Build a Merkle tree using the default SHA-256 hash function.
     *
     * @param data list of leaf hashes (transaction hashes)
     */
    public MerkleTree(List<String> data) {
        this(data, new Sha256Hasher());
    }

    /**
     * Build a Merkle tree with an injected hash function.
     *
     * @param data   list of leaf hashes (transaction hashes)
     * @param hasher hash function used for all internal node hashing
     */
    public MerkleTree(List<String> data, HashFunction hasher) {
        this.hasher = hasher;
        this.leaves = data == null ? new ArrayList<String>() : new ArrayList<>(data);
        if (!leaves.isEmpty()) {
            buildTree();
        }
    }

    /**
     * Build the complete tree bottom-up.
     *
     * ALGORITHM:
     * 1. Start with the leaf hashes.
     * 2. Pair adjacent nodes and hash each pair into a parent.
     *    An odd trailing node is paired with itself (duplicated).
     * 3. Repeat until a single root remains.
     *
     * TIME COMPLEXITY: O(n)
     */
    public void buildTree() {
        if (leaves.isEmpty()) {
            root = null;
            return;
        }

        List<MerkleNode> currentLevel = new ArrayList<>();
        for (String leaf : leaves) {
            currentLevel.add(new MerkleNode(leaf, null, null));
        }

        while (currentLevel.size() > 1) {
            List<MerkleNode> nextLevel = new ArrayList<>();

            for (int i = 0; i < currentLevel.size(); i += 2) {
                MerkleNode left = currentLevel.get(i);
                MerkleNode right = (i + 1 < currentLevel.size()) ? currentLevel.get(i + 1) : left;

                String combined = left.getHash() + right.getHash();
                MerkleNode parent = new MerkleNode(hasher.hash(combined), left, right);
                nextLevel.add(parent);
            }

            currentLevel = nextLevel;
        }

        root = currentLevel.get(0);
    }

    /**
     * @return the Merkle root, or null if the tree is empty
     */
    public String getMerkleRoot() {
        return root == null ? null : root.getHash();
    }

    /**
     * Generate a Merkle proof for a specific leaf hash.
     *
     * The proof lists the sibling hash at every level from the leaf to
     * the root, together with the side on which each sibling sits.
     *
     * COMPLEXITY: O(log n)
     *
     * @param targetHash the leaf hash to prove
     * @return the proof (empty if the hash is not a leaf of this tree)
     */
    public List<MerkleProofElement> generateProof(String targetHash) {
        List<MerkleProofElement> proof = new ArrayList<>();
        if (root != null) {
            findAndBuildProof(root, targetHash, proof);
        }
        return proof;
    }

    /**
     * Verify that a target hash belongs to the tree with the given root.
     *
     * Recombines the target with each proof element (respecting sides)
     * up to the root and compares the result with the expected root.
     *
     * COMPLEXITY: O(log n)
     *
     * @param targetHash the leaf hash being verified
     * @param proof      proof generated by {@link #generateProof(String)}
     * @param rootHash   the expected Merkle root
     * @return true if the proof reconstructs the root
     */
    public boolean verifyProof(String targetHash, List<MerkleProofElement> proof, String rootHash) {
        String currentHash = targetHash;

        for (MerkleProofElement element : proof) {
            String combined;
            if (element.getSide() == MerkleSide.LEFT) {
                // Sibling sits on the left of the concatenation.
                combined = element.getSiblingHash() + currentHash;
            } else {
                // Sibling sits on the right of the concatenation.
                combined = currentHash + element.getSiblingHash();
            }
            currentHash = hasher.hash(combined);
        }

        return currentHash.equals(rootHash);
    }

    /**
     * @return the number of levels in the tree (1 for a single leaf)
     */
    public int getTreeDepth() {
        return depth(root);
    }

    private int depth(MerkleNode node) {
        if (node == null) {
            return 0;
        }
        if (node.isLeaf()) {
            return 1;
        }
        return 1 + Math.max(depth(node.getLeft()), depth(node.getRight()));
    }

    /**
     * Depth-first search for the target leaf, collecting sibling hashes
     * along the path.
     */
    private boolean findAndBuildProof(MerkleNode node, String target, List<MerkleProofElement> proof) {
        if (node == null) {
            return false;
        }

        if (node.isLeaf()) {
            return node.getHash().equals(target);
        }

        if (node.getLeft() != null && findAndBuildProof(node.getLeft(), target, proof)) {
            // Found in the left subtree: the right sibling completes the proof.
            MerkleNode sibling = node.getRight() != null ? node.getRight() : node.getLeft();
            proof.add(new MerkleProofElement(sibling.getHash(), MerkleSide.RIGHT));
            return true;
        }

        if (node.getRight() != null && findAndBuildProof(node.getRight(), target, proof)) {
            // Found in the right subtree: the left sibling completes the proof.
            proof.add(new MerkleProofElement(node.getLeft().getHash(), MerkleSide.LEFT));
            return true;
        }

        return false;
    }

    /**
     * @return an unmodifiable view of the leaf hashes
     */
    public List<String> getLeaves() {
        return Collections.unmodifiableList(leaves);
    }
}
